### ISSUE TITLE
Ipfire were switched from http to https

### ISSUE THREAD

**Issue by Smookydope** [stdevel/check_pakfire#10]
Hi Christian.

The Ipfire mirrors were switched from http to https.

I think your script need an update on line 43 from

`	if "HTTP;" in line.rstrip():`

to

`	if "HTTPS;" in line.rstrip():`

Thx for your great work.

Best wishes,
Marcel

**Comment by stdevel** [comment]
Investigating on branch `bug-http_https_issue10`

**Comment by stdevel** [comment]
Hey Marcel,
thanks for your valuable feedback! I was able to reproduce and fix this issue. 👍 

Best wishes,
Christian.
