### ISSUE TITLE
-W / -C not working

### ISSUE THREAD

**Issue by ewiesmann** [stdevel/check_pakfire#17]
Hi Christian,

if I add command line options -W 0 or -C 0 check_pakfire.py (a39c539) allways reports "OK"

I added some changes in handling the integer values, print out performance output for core updates and also added a feature to check if a system reboot is needed when updates are done (see attached file "check_pakfire-diffs.txt")

Maybe you can incorporate the extensions into your code?

Greetings from Dortmund/Germany

Edgar

[check_pakfire_v1.3.0.py.txt](https://github.com/stdevel/check_pakfire/files/3088428/check_pakfire_v1.3.0.py.txt)
[check_pakfire-diff.txt](https://github.com/stdevel/check_pakfire/files/3088429/check_pakfire-diff.txt)

**Comment by stdevel** [comment]
Hey @ewiesmann,
first of all: welcome to GitHub! :)

Thanks for your code contribution, I will have a look at it in branch `feature-need_reboot-issue17`.

**Comment by stdevel** [comment]
Looks great - thank you again for sharing your code!

I will accept your merge request. 👍

**Comment by stdevel** [comment]
Fixed in commit bb25708eedd15ac4aebae857ffbf55f097ebc4d9.
