### ISSUE TITLE
script no longer works since the last update for Ipfire to Core 161

### ISSUE THREAD

**Issue by Smookydope** [stdevel/check_pakfire#19]
Hello.
Unfortunately, your script no longer works since the last update for Ipfire to Core 161. I think it has to do with the fact that Python is only available in version 3. 

Greetings
Marcel

**Comment by stdevel** [comment]
Hi @Smookydope - good point, thanks for pointing out!

I'm not using IPFire anymore but I will have a look at it - this shouldn't be too hard to fix.

**Comment by Smookydope** [comment]
Hi stdevel,
Thank you for your quick response and for taking care of the script even though you no longer use IPFire. Maybe it is still helpful for you to know that the Python on which IPFire is currently running in version 3.8.

Regards
Marcel

**Comment by stdevel** [comment]
You're welcome! I spun up an IPFire VM and did some improvements in branch `feat-python3`.

Could you try the updated script from here: https://github.com/stdevel/check_pakfire/blob/feat-python3/check_pakfire.py

I was able to check for updates:

```shell
# python3 check_pakfire.py -P
OK: Core update (161) up2date, packages up2date  | 'system_updates'=0;1;3;; 'outdated_packages'=0;1;5;;
```

**Comment by Smookydope** [comment]
Thanks.
Works perfectly.
I only changed the first line.
From #!/usr/bin/env python
to #!/usr/bin/env python3
So that I can call the script as follows:
/usr/lib/nagios/check_pakfire.py -w 1 -c 2 -e
 
regards
Marcel

**Comment by stdevel** [comment]
Good point - thanks for testing!
Just adopted your shebang line change and published a release.

Best wishes,
Christian.
